dist: xenial
services:
- postgresql
addons:
  chrome: stable
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install -U selenium
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- coverage run --branch --source=. ./manage.py test mixnet --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-edubotdom
  strategy: git
  api_key:
    secure: PxVlA7j5kL527f82gATOjG+kGQw1h4fK41K4TuHQE49/Bvgm5hoMO1EzytjvUVp0wQTdTiM8P0G7OX1phvTHTiXwKkV3ojYYRJYUjbl43dJUvi6XBZLc+I6oJNqZ+cHJMmxFiLR+n1XaHDuJSoXHQavoiuIVQ3XnBiU1Egf8i7m0GbO7fh5fvBi1p1+LqEI5gIDOlSe91A8tRhh03PeX2ausognUzvE5FlUmae48nm9UdBSbr0tRfsBT9ACWSHXieiPD6w1/5Jhbe5PIukp57dz0xgks0tbgbkjw5WoiTuGAor37Ss0PjRt3fdMZe1chHIOVeWbJOeq+avS8JBfygaChpaetvYs0XGS6z+ia7JZ9UquzWEMl5aucKdUfhq+gacy/zZyDgHA4cYkh+2my4X+jvibafWm6lbIWtN9fFNhUEepZ8xOlc8y5wcGUTjNhYT3eH9WtnhwkIvltuXxXFsLIA5FelaDsa55qphXnEg4xqvQWqBlvtsnK7ARbP6NAJjNTKymJH7tQlp2iIW5QpyjR88K6EB/nGNG1Ak3zAKOmaNnRyjhBsc2T4887Ms6mUhYjVzle3LYev192SCOR3pf14i6vv399CHEzyaRqZPPOSeveVy9t91o5emR1EEEUbzWiTdfGumWV5DucuC5Z0j+36Qvl4U6U/NbyBVrvpW8=
  on:
    branch: master
notifications:
  email:
    recipients:
    - edubotdom@alum.us.es
    on_success: always
    on_failure: always
