# Generated by Django 2.0 on 2020-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='manzana',
            field=models.TextField(default='verde'),
        ),
    ]
