# Generated by Django 2.0 on 2020-12-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_questionoption_manzana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='manzana',
        ),
    ]
