# Generated by Django 2.0 on 2020-12-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_questionoption_manzana'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorder',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
